### ISSUE TITLE
daemon/service -> concurrency

### ISSUE THREAD

**Issue by josh-devops-center** [nvie/rq#468]
Hi,

There seems to be no mechanism to daemonize or run django-rq as a service. For example, there is no WSGI interface.

The recommended way on the [documentation](https://github.com/ui/django-rq#deploying-on-heroku) front page is to run the worker inside a single process django context.

This is a severe limitation and precludes sizing hardware to match the workload.

This [issue](https://github.com/nvie/rq/issues/464) mentions to start multiple worker processes. Competing implementations such as [Celery](http://www.celeryproject.org/) offer WSGI and proper concurrency support.

As the name is django redis queue, there should be proper care and documentation explaining how concurrency is architected and how does one configure and scale the workers.

**Comment by selwin** [comment]
Hi there, `django-rq` doesn't need to provide a WSGI interface because it's already provided by Django. To deploy it in production, you can consult Django's documentation here: https://docs.djangoproject.com/en/1.7/howto/deployment/

RQ does not currently ship with any concurrency enabled workers, but since there are a few `gevent` based worker implementations around. This is one example: https://github.com/zhangliyong/rq-gevent-worker . 

In terms of documentation - yes, it could be a lot better and we welcome any help to improve it :)
