### ISSUE TITLE
worker.pid returns incorrect PID

### ISSUE THREAD

**Issue by swarnakumar** [nvie/rq#517]
worker.pid seems to return PID of the python interpreter process (where worker.pid is called from), rather than PID of the actual worker itself.

I am running two workers using ```rqworker``` command from shell.

When I open up python interpreter from shell, and try to get those workers:
```
workers = rq.Worker.all(connection = redis.Redis(host='localhost', port=6379))
for w in workers:
    print(w.pid)

14648
14648
```
14648 is the interpreter process's PID.

But worker.key seems to contain the correct pid
```
for w in workers:
   print(w.key)

rq:worker:macbook.14620
rq:worker:macbook.14561
```

I am using rq - 0.5.2, redis - 2.10.3, and Python 3.4.0

**Comment by joostdevries** [comment]
This is because pid is just a call to `os.getpid()` (https://github.com/nvie/rq/blob/master/rq/worker.py#L205) while the worker name (which is used in the key) is actually derived from the worker key stored in redis (https://github.com/nvie/rq/blob/master/rq/worker.py#L113).

So to get the right pid, the easiest solution would be to derive it from the name as well (chop it off the end of the string).

Probably add something like this to `__init__`
```python
if self._name:
  self._pid = os.path.splitext(self._name)[1][1:]
```

and then change the pid getter:

```python
    @property
    def pid(self):
        """The current process ID."""
        if self._pid:
          return self._pid
        return os.getpid()
```

**Comment by selwin** [comment]
I agree that this is a bug. PR to fix this is welcome :)

**Comment by nvie** [comment]
This is because the Worker class was never meant to be used as both a client and a server. If you instantiate `Worker('foo')` in two separate processes, they have no means to communicate. This was intentionally never intended as a use case.

I've always considered the `pid` property a private property of the Worker server, necessary to manage the forking behaviour, and to provide a unique worker key. In other words: an implementation detail. Not a means of communicating the process ID externally. (In fact, if I had used a different concurrency model by default, say threading, I'd have not recorded the pid, but the thread ID.)

What I do consider a bug though is my past decision to exposure the `Worker.all()` method publicly, which is the source of the confusion (and has been on multiple occasions in the past). The only use case for `Worker.all()` is logging/monitoring. There could have easily been a nicer API for that, i.e. imagine a `Runtime.get_running_worker_info()`, rather than `Worker.all()` and then misusing Worker instances for only the info. It's been a mis-design :(

**Comment by joostdevries** [comment]
@nvie I understand your point and I think it's wise not to encourage the use of `Worker` outside actual workers. Maybe a `WorkerInfo` class with an `all()` method would do the trick?

**Comment by selwin** [comment]
Something like this, perhaps?
```python
from rq import rqinfo

rqinfo.workers() # Returns a list of WorkerInfo instances
rqinfo.queues() # Returns a list of QueueInfo instances
```

**Comment by nvie** [comment]
Yes, that'd be a bit better already. I actually like a single `rq.runtime` module or class, for logging/inspection/monitoring purposes. I've seen a lot of misuse of the Worker/Job/Queue classes in the wild, simply because there is no other/proper way of getting that runtime information. Ideally, those runtime helpers would only pull data from Redis, and not inspect OS processes, etc.

**Comment by joostdevries** [comment]
@nvie @selwin Want to keep tracking the concept of `rq.runtime` in this issue or would it be better to track it in a dedicated issue? Because I think [repo:nvie/rq-dashboard](/nvie/rq-dashboard) will become a major consumer of that API ;-)

**Comment by selwin** [comment]
Yeah, please do. `rq-dashboard` also needs to be updated to support the newly introduced job registries. It's lagging behind [django-rq](https://github.com/ui/django-rq) in this regard.

**Comment by selwin** [comment]
Superseded by https://github.com/nvie/rq/issues/543
