### ISSUE TITLE
Error 'module' object has no attribute 'fork' under Windows 10

### ISSUE THREAD

**Issue by alkalinin** [nvie/rq#859]
I am trying to using rq under windows 10, but get an error in worker:
```
 File "c:\dev\src\rq\rq\worker.py", line 474, in work
    self.execute_job(job, queue)
  File "c:\dev\src\rq\rq\worker.py", line 592, in execute_job
    self.fork_work_horse(job, queue)
  File "c:\dev\src\rq\rq\worker.py", line 534, in fork_work_horse
    child_pid = os.fork()
AttributeError: 'module' object has no attribute 'fork'
```

**Comment by sschnug** [comment]
[Dcoumentation excerpt:](http://python-rq.org/docs/)

> Limitations
> RQ workers will only run on systems that implement fork(). Most notably, this means it is not possible to run the workers on Windows.

**Comment by W7PEA** [comment]
Windows Linux Subsystem supports FORK!!! 

The way to get this working, is:
1. You will need the Windows Linux Subsystem. as of not not widely released: https://docs.microsoft.com/en-us/windows/wsl/install-win10
2. Then you go to the Microsoft Store and install a linux distro and run  it.. (this actually does the install)
3. In your command prompt (or vs code terminal) you can then run bash and from there you can `pip install rq` and then run the worker.

**Comment by chineseqsc** [comment]
os.fork() only works with Linux operating systems, and with Win10 you can use the cross-platform **multiprocessing** module

**Comment by sankalpmukim** [comment]
Hey guys! This Python God I have on vc helped me a little. Try running this
`python -m pip install https://github.com/michaelbrooks/rq-win.git@c6e65e38f8a6ca99a0c8e0dd6fe35f9b92837cca`

If that doesn't work, try this:
`py -m pip install rq-win @ git+https://github.com/michaelbrooks/rq-win.git@c6e65e38f8a6ca99a0c8e0dd6fe35f9b92837cca`

but the thing would fail because both CMD and Powershell don't like @ at all. So put it in a requirements.txt file and do `py -m pip install -r requirements.txt`

**Comment by Trung0246** [comment]
Is it possible to use https://docs.python.org/3/library/multiprocessing.html` instead?

**Comment by selwin** [comment]
I’m open to changing the underlying worker to use multi processing. So please open a PR and I’ll review it.
